name: london-fire-response
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas=2.2.3
  - numpy=2.2.6
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - jupyterlab
  - ipykernel=6.21.2
  - openpyxl
  - xlrd
  - ipywidgets=8.0.4
  - nb_conda_kernels
  - jupyterlab-widgets=3.0.7
  - pip
  - pip:
      - pyod
      - statsmodels
      - plotly
      - plotly_express
      - plotly_resampler
