name: london-fire-response
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyterlab
  - ipykernel
  - openpyxl
  - xlrd
  - pip
  - pip:
      - jupyter
